server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0

#API Route Properties
spring:
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/department/**

        - id: employee-service
          uri: http://localhost:8082  #lb://employee-service if Load balance applicable
          predicates:
            - Path=/employee/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true



#Logger
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Enables DEBUG level logging for Gateway routes
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG  # Log request details
    org.springframework.cloud.gateway.filter: DEBUG  # Detailed logs for filters in the Gateway
    org.springframework.cloud.gateway.route: DEBUG
