server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

management:
  tracing:
    sampling:
      probability: 1.0

#DB Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-db
    username: root
    password: Arun01032001pro
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true